# Generated by Django 4.2.12 on 2024-05-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('has_contract', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('transport_hours', models.IntegerField(default=0)),
                ('transport_minutes', models.IntegerField(default=0)),
                ('hide_transport_charges', models.BooleanField(default=False)),
                ('tech1_regular_hours', models.IntegerField(default=0)),
                ('tech1_time_and_a_half_hours', models.IntegerField(default=0)),
                ('tech1_double_time_hours', models.IntegerField(default=0)),
                ('tech2_regular_hours', models.IntegerField(default=0)),
                ('tech2_time_and_a_half_hours', models.IntegerField(default=0)),
                ('tech2_double_time_hours', models.IntegerField(default=0)),
                ('tech3_regular_hours', models.IntegerField(default=0)),
                ('tech3_time_and_a_half_hours', models.IntegerField(default=0)),
                ('tech3_double_time_hours', models.IntegerField(default=0)),
            ],
        ),
    ]
