# Generated by Django 4.2.13 on 2024-05-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='hours_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
