# Generated by Django 4.2.13 on 2024-05-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='hours_on_contract',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
