# Generated by Django 4.2.13 on 2024-07-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='user_profile',
        ),
    ]
