# Generated by Django 4.2.13 on 2024-05-31 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_hours_on_contract_customer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='hours_on_contract',
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=10),
        ),
    ]
