# Generated by Django 4.2.13 on 2024-05-31 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_remove_customer_hours_on_contract_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='last_modified',
        ),
    ]
