# Generated by Django 4.2.13 on 2024-07-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customer_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='renewal_paid',
            field=models.BooleanField(default=False),
        ),
    ]
