# Generated by Django 4.2.13 on 2024-05-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_remove_customer_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='hours_remaining',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
