# Generated by Django 4.2.13 on 2024-06-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customer_hours_remaining'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.AlterField(
            model_name='customer',
            name='hours_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='reference_emails',
            field=models.ManyToManyField(blank=True, to='customers.emailreference'),
        ),
    ]
