# Generated by Django 4.2.13 on 2024-06-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_emailreference_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='reference_emails',
            new_name='emails',
        ),
    ]
