# Generated by Django 4.2.13 on 2024-07-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_remove_customer_renewal_paid_timesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
