# Generated by Django 4.2.13 on 2024-07-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_timesheet_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='manual_charge_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='manual_charge_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
