# Generated by Django 4.2.13 on 2024-06-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_alter_customer_hours_remaining_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='hours_remaining',
            field=models.IntegerField(default=0),
        ),
    ]
