# Generated by Django 4.2.13 on 2024-07-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_contract_approved_contract_manual_charge_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date',
            field=models.CharField(max_length=8),
        ),
    ]
