# Generated by Django 4.2.13 on 2024-05-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_alter_timesheet_technician_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='rate',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='special_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
