# Generated by Django 4.2.13 on 2024-07-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_timesheet_display_notes_to_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='pause',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='pause_hours',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='pause_minutes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
