# Generated by Django 4.2.13 on 2024-07-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0003_remove_timesheet_pause_timesheet_pause_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='pause_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='pause_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
