# Generated by Django 4.2.13 on 2024-05-27 16:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0003_remove_timesheet_rate_timesheet_special_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='timesheet_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
