# Generated by Django 4.2.13 on 2024-07-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0004_alter_timesheet_date_alter_timesheet_pause_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.CharField(max_length=8),
        ),
    ]
