# Generated by Django 4.2.13 on 2024-05-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0004_alter_timesheet_timesheet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='technician_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timesheet',
            name='total_time_used',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
