# Generated by Django 4.2.13 on 2024-05-30 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_technician'),
        ('timesheets', '0006_remove_timesheet_technician_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('has_contract', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('transport_hours', models.IntegerField(default=0)),
                ('transport_minutes', models.IntegerField(default=0)),
                ('hide_transport_charges', models.BooleanField(default=False)),
                ('hours_remaining', models.IntegerField(default=0)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('tech1_regular_hours', models.IntegerField(default=0)),
                ('tech1_time_and_a_half_hours', models.IntegerField(default=0)),
                ('tech1_double_time_hours', models.IntegerField(default=0)),
                ('tech2_regular_hours', models.IntegerField(default=0)),
                ('tech2_time_and_a_half_hours', models.IntegerField(default=0)),
                ('tech2_double_time_hours', models.IntegerField(default=0)),
                ('tech3_regular_hours', models.IntegerField(default=0)),
                ('tech3_time_and_a_half_hours', models.IntegerField(default=0)),
                ('tech3_double_time_hours', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='timesheet',
            name='total_time_used',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='technician',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customers.technician'),
        ),
    ]
