# Generated by Django 4.2.13 on 2024-05-30 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_technician'),
        ('timesheets', '0007_customer_technician_timesheet_total_time_used_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Technician',
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.technician'),
        ),
    ]
