# Generated by Django 4.2.13 on 2024-06-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0008_delete_customer_delete_technician_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
