# Generated by Django 4.2.13 on 2024-06-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0009_timesheet_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='timesheets/'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='timesheet_id',
            field=models.CharField(max_length=100),
        ),
    ]
