# Generated by Django 4.2.13 on 2024-06-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0010_alter_timesheet_file_alter_timesheet_timesheet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='pause',
            field=models.CharField(default='0h0', max_length=10),
        ),
    ]
